[server]
fileWatcherType = "poll"

[client]
toolbarMode = "minimal"

[theme]
primaryColor="#FF4B4B"
#backgroundColor="#FFFFFF"
backgroundColor="#52be80"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"